### ISSUE TITLE
Building not making .dlls for first step, only .libs

### ISSUE THREAD

**Issue by GeminiSquishGames** [Dudejoe870/godot-openmpt#2]
Using Visual Studio 2022, I use the default debug, build all and it's successful. I make the release config and build all as well, successful. So both build, I have gen folders, but make only .lib files so I have no .dll files to drop into the bin of the root godot-cpp. Am I doing something wrong?

Getting a lot of the warning: 
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Warning	D9025	overriding '/W3' with '/W4'	D:\dev\godot_extentions\godot libopenmpt\godot-openmpt\godot-cpp\out\build\x64-Debug\godot-cpp	D:\dev\godot_extentions\godot libopenmpt\godot-openmpt\godot-cpp\out\build\x64-Debug\cl	1		

```

**Comment by Dudejoe870** [comment]
Those warnings shouldn't matter. I've been messing with the build system a lot yesterday, as right now the output DLLs are huge (like over 100mb) because of a bunch of useless debug information that I'm trying to find the right compile flags to get rid of. Also, godot-cpp only makes .lib files. they get linked statically into the output dll, so that is expected if you're only building godot-cpp here.

**Comment by GeminiSquishGames** [comment]
Ah, lol. I had wondered! Okay thanks for that.

**Comment by GeminiSquishGames** [comment]
Not sure how else to get back to you but here. Everything seems to be
working very well. I noticed that the DirectX effects that ModPlugTracker
can set per channel and on a master bus can be set. One per channel and a
chain of them on the master. So even EQ and Compression without using the
AudioStreamPlayer with a specific bus. So very handy and thank you again.
I'll probably tinker with things and try getting anything else I need to
work in C# when I can. The only thing left is tapping into the sample and
instrument memory and changing samples or swapping them out, ideally with
sample packs and instrument files native to .IT, or the toughie is treating
the sample in memory like it was a buffer, then soft synths can be a thing
maybe.
