### ISSUE TITLE
`select_subsong` and `get_selected_subsong` methods are duplicate

### ISSUE THREAD

**Issue by RedMser** [Dudejoe870/godot-openmpt#6]
They exist in both `AudioStreamMPT` and `AudioStreamPlaybackMPT`.

~It should likely be removed from the latter class, since you do not need a playback to select / get selected subsong.~

**Comment by RedMser** [comment]
Actually I misunderstood, the `mpt_module` is obviously not shared between the stream itself and each playback.

So the better question is which one the user has to change under what condition. e.g. for the use case of seeking to a specific subsong (either on load, or during playback).

I couldn't get anything working in my multi-song track. Maybe I misunderstand how the method works, but at the same time the documentation on it is really poor from the library's side.

**Comment by GeminiSquishGames** [comment]
It works for me by using select_subsong(sequence_number - 1) to set the sequence/subsong. Did you build from the source or use the prebuilt branch contents? (Probably need to put that in the releases section at some point...) There may be some differences. 

get_selected_subsong returns an int, and is there to know what subsong is selected at that time so it's a return, 

@Dudejoe870 I guess make some of these more GDScript like naming too, that might help interpret some of the functionality to GDScript users. Most things are get_thing and set_thing, or given the get/set combo as a property.

**Comment by RedMser** [comment]
Self-built from master, I can share a demo project later. Do you call select_subsong on the stream or the playback? Before or after calling play()?

Also just to confirm, it should automatically seek to the start of a subsong, or do I need to do this manually?

Thanks for any help.

**Comment by GeminiSquishGames** [comment]
The playback, sorry, that would be important to know, and it will start over on it's own, as well as if you call the same subsong again.

**Comment by Dudejoe870** [comment]
I didn't test everything, but the reason why it's also in the stream class, is for getting metadata about subsongs (I am not entirely sure if you can even do that though, I was thinking of adding an example project and actually testing more things about how the API works, because rn it's just a direct translation of libopenmpt. I sort of guessed what functions would be useful in which class)

**Comment by RedMser** [comment]
I will check again in a few days when I have time (exam period right now) and see if I did something wrong or if I found some kind of bug or silent error case.

But if it is not too much trouble, receiving a simple example project with `select_subsong` confirmed to be working properly would also help to see what I did wrong maybe.

**Comment by GeminiSquishGames** [comment]
for now, I can show what should get it going. I need to organize my repositories and I'll get something up when I get back from the field in a bit. I can at least contribute my test bed as a repo in a bit, I'll work on getting as much of the functionality in one go and make it easy to look at tonight.

```
extends AudioStreamPlayer

var current_subsong = 0
var my_mptpb : AudioStreamPlaybackMPT

func play_sfx():
    play() # playback
    if has_stream_playback(): # make sure before trying things due to crashes if null
        print("has playback")
        my_mptpb = get_stream_playback()
        my_mptpb.select_subsong(1) # should switch to start of next sequence/subsong, #2 in MPT
        # Hrrmm, not auto completing props/metho in editor after the last two ???
        print("subsong: ", my_mptpb.get_selected_subsong()) 
        
    else:
        print("No PLAYBACK AAAH!!!")

```

**Comment by GeminiSquishGames** [comment]
I've got my test bed here: https://github.com/GeminiSquishGames/libopenmpt-test-bed

The readme has what I've got so far. I need to test a bunch of things and over the week should add examples of each method in use cases. Hopefully that helps in some way. I'll probably be using it to make tutorials as well if I can get all of my projects to play nice in my head.

**Comment by RedMser** [comment]
Thanks for the help, I tried it as described and it works now. Specifically:

1. `play()`
2. `get_stream_playback().select_subsong(n)` 

I was doing it on the stream instead, since I assumed that would be the "initial subsong", but as explained it seems to be related to metadata stuff possibly.
