### ISSUE TITLE
Add support for some CTL keys

### ISSUE THREAD

**Issue by RedMser** [Dudejoe870/godot-openmpt#7]
I don't think a generic "get/set ctl" API makes sense, since a lot of keys are already available through a nicer API. But some keys could be helpful to expose with a wrapper API, such as:

- load.skip_plugins (boolean): Set to "1" to avoid loading plugins
- load.skip_subsongs_init (boolean): Set to "1" to avoid pre-initializing sub-songs. Skipping results in faster module loading but slower seeking.
- seek.sync_samples (boolean): Set to "0" to not sync sample playback when using openmpt_module_set_position_seconds or openmpt_module_set_position_order_row.

I propose the `load.*` CTLs to be available as import options and corresponding properties on the stream class.
`seek.*` would make sense to be part of the playback, and it seems like each playback gets its own `mpt_module` (thus its own ctls). But maybe it could also be set on the stream, so that each playback gets this value assigned automatically?

**Comment by Dudejoe870** [comment]
Latest commit 2892d65 has added this feature :)

**Comment by RedMser** [comment]
Thanks for the quick implementation! This is a really useful project, your work is much appreciated :)
