### ISSUE TITLE
Web build?

### ISSUE THREAD

**Issue by jeffinitup** [Dudejoe870/godot-openmpt#9]
Will you ever release binaries for web exports? I've tried to build a web binary myself, but outside of following the build instructions given (which do work) I haven't been able to get very far

**Comment by GeminiSquishGames** [comment]
I'm assuming you are looking at https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_web.html? If so, you can ignore the rest of this reply. I don't know how to help get around not being able to compile the export templates but it's usually better than having to compile the engine from scratch.

I ran into this also so it kinda bummed me out. Issue being: "The default export templates do not include GDExtension support for performance and compatibility reasons. " So you have to compile your own web export template with the option [dlink_enabled=yes] to have it build the .wasm objects on web export, which is a hassle and one of the reasons GDExtensions are hampered by technical BS for cross-platform development in general. It's almost worth having your own build of Godot just to incorporate everything into modules and forgetting about GDExtention except it has promise— I think. If they encapsulated the process of creating the initial <insert your compiled language here> project and making custom export template compilation a function for you within the editor, it would be a snap but it's ducttape at best ATM, IMHO.

**Comment by jeffinitup** [comment]
Thank you for the reply, I was going at this pretty late at night and I glossed over the fact that the default export template doesn't include GDExtension support. I'll eventually have to cross this hurdle for my own project, but it's not a big priority right now. Thank you for the insight 😄 I'll go ahead and close this issue
